###################################################################

# Created by write_sdc on Mon Feb 15 20:19:29 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {address[31]}]
set_load -pin_load 3.40189 [get_ports {address[30]}]
set_load -pin_load 3.40189 [get_ports {address[29]}]
set_load -pin_load 3.40189 [get_ports {address[28]}]
set_load -pin_load 3.40189 [get_ports {address[27]}]
set_load -pin_load 3.40189 [get_ports {address[26]}]
set_load -pin_load 3.40189 [get_ports {address[25]}]
set_load -pin_load 3.40189 [get_ports {address[24]}]
set_load -pin_load 3.40189 [get_ports {address[23]}]
set_load -pin_load 3.40189 [get_ports {address[22]}]
set_load -pin_load 3.40189 [get_ports {address[21]}]
set_load -pin_load 3.40189 [get_ports {address[20]}]
set_load -pin_load 3.40189 [get_ports {address[19]}]
set_load -pin_load 3.40189 [get_ports {address[18]}]
set_load -pin_load 3.40189 [get_ports {address[17]}]
set_load -pin_load 3.40189 [get_ports {address[16]}]
set_load -pin_load 3.40189 [get_ports {address[15]}]
set_load -pin_load 3.40189 [get_ports {address[14]}]
set_load -pin_load 3.40189 [get_ports {address[13]}]
set_load -pin_load 3.40189 [get_ports {address[12]}]
set_load -pin_load 3.40189 [get_ports {address[11]}]
set_load -pin_load 3.40189 [get_ports {address[10]}]
set_load -pin_load 3.40189 [get_ports {address[9]}]
set_load -pin_load 3.40189 [get_ports {address[8]}]
set_load -pin_load 3.40189 [get_ports {address[7]}]
set_load -pin_load 3.40189 [get_ports {address[6]}]
set_load -pin_load 3.40189 [get_ports {address[5]}]
set_load -pin_load 3.40189 [get_ports {address[4]}]
set_load -pin_load 3.40189 [get_ports {address[3]}]
set_load -pin_load 3.40189 [get_ports {address[2]}]
set_load -pin_load 3.40189 [get_ports {address[1]}]
set_load -pin_load 3.40189 [get_ports {address[0]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[31]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[30]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[29]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[28]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[27]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[26]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[25]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[24]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[23]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[22]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[21]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[20]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[19]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[18]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[17]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[16]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[15]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[14]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[13]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[12]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[11]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[10]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[9]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[8]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[7]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[6]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[5]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[4]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[3]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[2]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[1]}]
set_load -pin_load 3.40189 [get_ports {address_data_memory[0]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[31]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[30]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[29]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[28]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[27]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[26]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[25]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[24]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[23]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[22]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[21]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[20]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[19]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[18]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[17]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[16]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[15]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[14]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[13]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[12]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[11]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[10]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[9]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[8]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[7]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[6]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[5]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[4]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[3]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[2]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[1]}]
set_load -pin_load 3.40189 [get_ports {write_data_data_memory[0]}]
set_load -pin_load 3.40189 [get_ports mem_write]
set_load -pin_load 3.40189 [get_ports mem_read]
create_clock [get_ports clk]  -name MY_CLK  -period 3.4  -waveform {0 1.7}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports rst]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_data_memory[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_memory[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_data_memory[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports mem_write]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports mem_read]
